version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.1.0
    volumes:
      - ./docker-volumes/es-data:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
    ports:
      - 9300:9300
      - 9200:9200

  server:
    image: server
    build: ./server
    depends_on:
      - elasticsearch
    ports:
      - 3001:80
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run start
    environment:
      discovery.type: single-node
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
